spring.application.name=maypointApp
spring.data.mongodb.uri=mongodb+srv://ronaldmanning2004_db_user:TI4SIYpGlbhBPUbH@waypointapp.sw01wqr.mongodb.net/?appName=WaypointApp
spring.data.mongodb.database=waypoints

